name: 'Query Bilibi User Info'
description: ''

inputs:
  mid:
    description: 'mid of the user to monitor'
    required: true
  page_url:
    description: 'url for getting personal page'
    required: true
  api_url:
    description: 'url for querying info'
    required: true
  target:
    description: 'Target follower number'
    required: true
  user_email:
    description: 'email for sending notification'
    required: true
  user_pass:
    description: 'password of the sender email'
    required: true
  receiver_email:
    description: 'email to receive notification'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'