#.github/worklows/scheduled-query.yaml
name: 'Scheduled Query.'
on:
  schedule:
    # runs every minutes
    - cron: '*/1 * * * *'

jobs:
  query:
    name: 'Query User Info'
    runs-on: macos-latest
    steps:
      - name: Query
        uses: YangchenYe323/bilibili-capturer@master
        with:
          mid: ${{ secrets.MID }}
          page_url: ${{ secrets.PAGE_URL }}
          api_url: ${{ secrets.API_URL }}
          target: ${{ secrets.TARGET }}
